microsoft/SandDance

- packages/azdata-sanddance/package.json
- packages/sanddance/src/legend.ts
- packages/vscode-sanddance/package.json
> remove duplicate legend elements

- packages/office-ui-fabric-react-cdn-typings/index.d.ts
- packages/sanddance-app/src/fabricComponents.ts
- packages/sanddance-explorer/src/controls/columnMap.tsx
- packages/sanddance-explorer/src/controls/signal.tsx
- packages/sanddance/src/defaults.ts
- packages/sanddance/src/specs/constants.ts
- packages/sanddance/src/specs/scales.ts
- packages/sanddance/src/specs/scatterPlot/index.ts
- packages/sanddance/src/specs/scatterPlot/scales.ts
- packages/sanddance/src/specs/scatterPlot/signals.ts
- packages/sanddance/src/specs/signals.ts
- packages/sanddance/src/specs/stableBarChart/index.ts
- packages/sanddance/src/specs/stableBarChart/scales.ts
- packages/sanddance/src/specs/stableBarChart/signals.ts
- packages/sanddance/src/specs/treeMap/index.ts
- packages/sanddance/src/specs/treeMap/signals.ts
- packages/sanddance/src/specs/types.ts
> Added Color reverse Signal

- packages/powerbi-visual-sanddance/capabilities.json
- packages/powerbi-visual-sanddance/pbiviz.json
- packages/powerbi-visual-sanddance/src/vega.d.ts
- packages/powerbi-visual-sanddance/src/visual.ts
- packages/powerbi-visual-sanddance/style/visual.less
- packages/powerbi-visual-sanddance/tsconfig.json
- packages/sanddance/src/types.ts
- packages/sanddance/src/viewer.ts
> PowerBI updates

- packages/azdata-sanddance/src/extension.ts
Made changes to extensions.ts to fix JSON parser.
> Fixed JSON parser

- packages/sanddance/src/specs/inference.ts
- packages/sanddance/src/specs/types.ts
> added mean to ColumnStats

- packages/sanddance-react/src/viewer.tsx
- packages/sanddance/src/tooltip.tsx
- packages/sanddance/src/viewer.ts
Clip tooltip when height is constrained
> Tooltip size

- packages/azdata-sanddance/package.json
- packages/vscode-sanddance/package.json
> Add editor title context menu

- packages/powerbi/capabilities.json
- packages/powerbi/pbiviz.json
- packages/powerbi/src/app.ts
- packages/powerbi/src/data.ts
- packages/powerbi/src/settings.ts
- packages/powerbi/src/visual.ts
- packages/sanddance-explorer/src/controls/dataItem.tsx
- packages/sanddance-explorer/src/dialogs/chart.tsx
- packages/sanddance-explorer/src/explorer.tsx
- packages/sanddance/src/constants.ts
- packages/sanddance/src/details.tsx
- packages/sanddance/src/searchExpression/exec.ts
- packages/sanddance/src/specs/constants.ts
- packages/sanddance/src/specs/density/data.ts
- packages/sanddance/src/specs/density/marks.ts
- packages/sanddance/src/specs/stableBarChart/marks.ts
- packages/sanddance/src/specs/stableBarChart/scales.quantitative.ts
- packages/sanddance/src/specs/stableBarChart/transform.quantitative.ts
- packages/sanddance/src/tooltip.tsx
- packages/sanddance/src/util.ts
> Powerbi filters other visuals

- packages/powerbi/package.json
- packages/powerbi/scripts/version.js
- packages/powerbi/src/app.ts
- packages/powerbi/src/language.ts
- packages/powerbi/src/version.ts
- packages/powerbi/style/visual.less
- packages/sanddance-explorer/src/columns.ts
- packages/sanddance-explorer/src/css/sidebar.scss
- packages/sanddance-explorer/src/dialogs/settings.tsx
- packages/sanddance-explorer/src/explorer.tsx
- packages/sanddance/src/tooltip.tsx
- packages/sanddance/src/types.ts
> Power BI fixes for MacOS/Safari

- package.json
- packages/powerbi/package.json
- packages/powerbi/src/visual.ts
- packages/sanddance/src/searchExpression/exec.ts
- packages/sanddance/src/specs/top.ts
- packages/sanddance/src/vega-deck.gl/marks/interfaces.ts
- packages/sanddance/src/vega-deck.gl/marks/legend.ts
- packages/sanddance/src/vega-deck.gl/marks/text.ts
> Powerbi tools update

- packages/powerbi/capabilities.json
- packages/powerbi/src/app.ts
- packages/powerbi/src/language.ts
- packages/powerbi/src/visual.ts
- packages/powerbi/style/visual.less
- packages/sanddance/src/css/sanddance.scss
- packages/sanddance/src/specs/density/marks.ts
- packages/sanddance/src/specs/grid/marks.ts
- packages/sanddance/src/specs/scatterPlot/marks.ts
- packages/sanddance/src/specs/selection.ts
- packages/sanddance/src/specs/stableBarChart/marks.ts
- packages/sanddance/src/specs/stableBarChart/scales.ts
- packages/sanddance/src/specs/treeMap/marks.ts
- packages/sanddance/src/vega-deck.gl/cube-layer/cube-layer-vertex.glsl.ts
- packages/sanddance/src/vega-deck.gl/defaults.ts
- packages/sanddance/src/vega-deck.gl/index.ts
- packages/sanddance/src/viewer.ts
- powerbi.md
This PR allows incremental loading of large data sets in Power BI.
> Use Power BI fetch API

- packages/sanddance-explorer/src/controls/sidebar.tsx
- packages/sanddance-explorer/src/css/columnMap.scss
- packages/sanddance-explorer/src/css/sidebar.scss
- packages/sanddance/src/vega-deck.gl/layers.ts
> Pin sidebar fix

- dev.md
This adds missing URLs in `dev.md`.
> Fix missing URLs in `dev.md`

- packages/powerbi/src/app.ts
- packages/powerbi/src/visual.ts
- packages/sanddance-explorer/src/explorer.tsx
- packages/sanddance/src/types.ts
- packages/sanddance/src/viewer.ts
> selected data triggers PowerBI selectionManager

- packages/sanddance/src/vega-deck.gl/marks/text.ts
> return default values for text mark

- packages/powerbi/capabilities.json
- packages/powerbi/package.json
- packages/powerbi/src/app.ts
- packages/powerbi/src/cleanInsight.ts
- packages/powerbi/src/convertFilter.ts
- packages/powerbi/src/visual.ts
- packages/sanddance-explorer/src/controls/searchTerm.tsx
- packages/sanddance-explorer/src/dialogs/search.tsx
- packages/sanddance-explorer/src/explorer.tsx
- packages/sanddance/src/viewer.ts
> Filter PowerBI instead of Selecting

- README.md
- dev.md
- docs/tests/v3/umd/sanddance-specs.html
- package-lock.json
- package.json
- packages/chart-recommender/test/recommend.js
- packages/sanddance-specs/README.md
- packages/sanddance-specs/package-lock.json
- packages/sanddance-specs/package.json
- packages/sanddance-specs/rollup.config.js
- packages/sanddance-specs/src/build.ts
- packages/sanddance-specs/src/index.ts
- packages/sanddance-specs/test/demo.js
- packages/sanddance-specs/test/perf.js
- packages/sanddance-vue/.gitignore
- packages/sanddance-vue/README.md
- packages/sanddance-vue/build/rollup.config.js
- packages/sanddance-vue/package-lock.json
- packages/sanddance-vue/package.json
- packages/sanddance-vue/scripts/docs.js
- packages/sanddance-vue/src/SandDanceVue.ts
- packages/sanddance-vue/src/SandDanceVue.vue
- packages/sanddance-vue/src/util.ts
- packages/sanddance-vue/src/version.ts
- packages/sanddance-vue/src/wrapper.js
- packages/sanddance-vue/tsconfig.json
- packages/sanddance/package.json
- packages/sanddance/rollup.config.js
- packages/sanddance/src/viewer.ts
- packages/vega-deck.gl/rollup.config.js
I've ported the React.js component to Vue, while using Vue's event system instead of callbacks.
E.g.
```
<SandDanceVue
@mounted="function"
@error="function"
@view="function"
/>
```
Resolves #211.
> Vue.js component

- packages/sanddance/src/types.ts
- packages/sanddance/src/viewer.ts
- packages/vega-deck.gl/src/interfaces.ts
- packages/vega-deck.gl/src/layers.ts
- packages/vega-deck.gl/src/presenter.ts
fixes #78
(partially fixes #127)
Although these are Japanese letters, they are basically same as Chinese in terms of charset.
> Add characterSet prop

- packages/vega-deck.gl/src/easing.ts
- packages/vega-deck.gl/src/layers.ts
- packages/vega-deck.gl/src/presenter.ts
> correct easing at 0 & 1

- .vscode/launch.json
- extensions/azdata-sanddance/CHANGELOG.md
- extensions/azdata-sanddance/package-lock.json
- extensions/azdata-sanddance/package.json
- extensions/azdata-sanddance/src/extension.ts
- extensions/vscode-sanddance/CHANGELOG.md
- extensions/vscode-sanddance/package-lock.json
- extensions/vscode-sanddance/package.json
- extensions/vscode-sanddance/src/extension.ts
> VSCode updates

- packages/sanddance-specs/package-lock.json
- packages/sanddance-specs/package.json
- packages/sanddance-specs/src/layouts/stack.ts
> fix stacks layout for small number of items

- package-lock.json
- packages/powerbi/package-lock.json
Reverts microsoft/SandDance#405
> Revert "Bump follow-redirects from 1.14.6 to 1.14.8"

- packages/sanddance-explorer/src/explorer.tsx
- packages/sanddance/src/tooltip.tsx
- packages/sanddance/src/types.ts
- packages/sanddance/src/viewer.ts
> Add TooltipCreateOptions, TooltipDestroyable

- packages/sanddance/src/viewer.ts
- packages/vega-morphcharts/src/interfaces.ts
- packages/vega-morphcharts/src/presenter.ts
> save color scheme for presenter

- packages/sanddance/src/viewer.ts
- packages/vega-morphcharts/src/morphcharts/axes.ts
- packages/vega-morphcharts/src/morphcharts/text.ts
- packages/vega-morphcharts/src/stagers.ts
> Fix z axis grid

- docs/tests/sanddance-specs/v1/js/sanddance-specs.js
- docs/tests/sanddance-specs/v1/specs/scatter.json
- packages/sanddance-explorer/src/dialogs/chart.tsx
- packages/sanddance-specs/package-lock.json
- packages/sanddance-specs/package.json
- packages/sanddance-specs/src/charts/barchartH.ts
- packages/sanddance-specs/src/charts/barchartV.ts
- packages/sanddance-specs/src/charts/density.ts
- packages/sanddance-specs/src/charts/grid.ts
- packages/sanddance-specs/src/charts/scatterplot.ts
- packages/sanddance-specs/src/charts/strips.ts
- packages/sanddance-specs/src/charts/treemap.ts
- packages/sanddance-specs/src/layouts/scatter.ts
- packages/sanddance-specs/src/layouts/square.ts
- packages/sanddance-specs/src/layouts/strip.ts
- packages/sanddance-specs/src/layouts/treemap.ts
- packages/sanddance-specs/src/types.ts
- packages/vega-morphcharts/package-lock.json
- packages/vega-morphcharts/package.json
- packages/vega-morphcharts/src/marks/rect.ts
> Scatter z-paint in 2d

- packages/vega-morphcharts/package-lock.json
- packages/vega-morphcharts/package.json
- packages/vega-morphcharts/src/morphcharts/axes.ts
> Fix z axis order

- packages/sanddance-explorer/package-lock.json
- packages/sanddance-explorer/package.json
- packages/sanddance-explorer/src/explorer.tsx
> Revive background image

- packages/sanddance-embed/README.md
- packages/sanddance-embed/package-lock.json
- packages/sanddance-embed/package.json
- packages/sanddance-embed/src/sanddance-embed.ts
- packages/sanddance-embed/src/types/message-request.d.ts
- packages/sanddance-embed/src/types/message-response.d.ts
- packages/sanddance/package-lock.json
- packages/sanddance/package.json
- packages/sanddance/src/types.ts
- packages/sanddance/src/viewer.ts
> Embed onselection event

- docs/docs/sanddance-explorer/v4/classes/Explorer_Class.html
- docs/docs/sanddance-explorer/v4/index.html
- docs/docs/sanddance-explorer/v4/interfaces/controls.IDialogProps.html
- docs/docs/sanddance-explorer/v4/modules.html
- packages/sanddance-explorer/README.md
- packages/sanddance-explorer/package-lock.json
- packages/sanddance-explorer/package.json
> Add styling info to Explorer Readme

- packages/sanddance-explorer/src/dialogs/backgroundImageEditor.tsx
> Fix background image for Power BI Desktop
